### ISSUE TITLE
tour: Explain in which case the implementation of an exercise fails

### ISSUE THREAD

**Issue by Adeynack** [golang/tour#462]
Context: https://tour.golang.org/methods/22

I implemented this exercise locally (using _GOLAND_). I wrote some test cases and they all work well. However, on the _Tour_, it fails with this output:

```
panic: runtime error: index out of range

goroutine 1 [running]:
main.MyReader.Read(0x10458000, 0x400, 0x800, 0xee840, 0x27301, 0xe57, 0x10458000, 0x3)
	/tmp/sandbox815971007/main.go:16 +0x60
golang.org/x/tour/reader.Validate(0x1287b0, 0x1953e0)
	/go/src/golang.org/x/tour/reader/validate.go:17 +0x1e0
main.main()
	/tmp/sandbox815971007/main.go:22 +0x40

Program exited.
```

I am unable to recreate this error and would then suggest as a general rule for the exercise slides that they output the value they are calling our implementations with so we can understand in which corner cases we fail to implement.

**Comment by Adeynack** [comment]
For the records, here is my actual implementation:

```go
func (r MyReader) Read(buffer []byte) (int, error) {
	bufferCap := cap(buffer)
	if bufferCap == 0 {
		return 0, nil
	}
	for i := 0; i < bufferCap; i++ {
		buffer[i] = 'A'
	}
	return bufferCap, nil
}
```

**Comment by WheeskyJack** [comment]
Hi,
above error is thrown when program tries to access the index of the slice which has not been added yet. 
So, when the length and capacity of the slice differs, you might be able to recreate the scenario.
Here is the playground snippet on how it can be recreated.
https://play.golang.org/p/3RFgRsmX5_e

One suggestion to your code can be to try using len() instead of cap().
BR.
